# Generated by Django 5.1.1 on 2024-09-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
